name: Manual Trigger For Browser
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        type: choice
        required: true
        options:
          - chrome
          - firefox
          - webkit
jobs:
  run-selective-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install ${{ github.event.inputs.browser }} --with-deps
    - name: Run Playwright tests
      run: TEST_EMAIL=${{ env.TEST_EMAIL }} npx playwright test --project=${{ github.event.inputs.browser }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
